In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv('Iris.csv')

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['SepalLengthCm'], y=df['PetalLengthCm'], z=df['PetalWidthCm'],
              color=df['Species'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [8]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [9]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[ 1.00671141  0.72148618 -0.40039813]
 [ 0.72148618  1.00671141 -0.11010327]
 [-0.40039813 -0.11010327  1.00671141]]


In [10]:
# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [11]:
eigen_values

array([1.88174415, 0.22463447, 0.91375561])

In [12]:
eigen_vectors

array([[ 0.68540625,  0.72456776,  0.07224842],
       [ 0.61432392, -0.62866836,  0.4768461 ],
       [-0.39092761,  0.28244937,  0.87601253]])

In [15]:
pc = eigen_vectors[0:2]
pc

array([[ 0.68540625,  0.72456776,  0.07224842],
       [ 0.61432392, -0.62866836,  0.4768461 ]])

In [18]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['Species'] = df['Species'].values
new_df.head()

PC1       PC2      Species
0 -1.757310  0.001392  Iris-setosa
1 -2.000662 -0.383790  Iris-setosa
2 -2.126985  0.003434  Iris-setosa
3 -2.215669 -0.016548  Iris-setosa
4 -1.765070  0.244660  Iris-setosa

In [21]:
new_df['Species'] = new_df['Species'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['Species'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()